scheb_two_factor:
    google:
        issuer: MintMe.com
        enabled: true
        template: security/2fa_login.html.twig

    backup_codes:
        enabled: true

    email:
        enabled: true
        sender_email: '%env(MAILER_USER)%'
        sender_name: MintMe.com
        digits: 6
        template: security/email_login.html.twig
        mailer: app.mailer

    # ip_whitelist:
    #     - 127.0.0.1

    trusted_device:
        enabled: '%trusted_device_enabled%'
        lifetime: '%trusted_device_cookie_lifetime%'
        extend_lifetime: '%trusted_device_extend_lifetime%'
