twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/public': public
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/fields.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
    globals:
        global_youtube_client_id: '%env(YOUTUBE_CLIENT)%'
        global_facebook_app_id: '%env(FACEBOOK_CLIENT)%'
        viabtc_offset: '%env(VIABTC_OFFSET)%'
        version: '%version%'
        is_beta_version: '%is_beta_version%'
        global_websocket_url: '%env(WEBSOCKET_URL)%'
        global_coinbase_url: '%coinbase_api_url%'
        google_tracking_id: '%google_tracking_id%'
        tawk_api_key: '%tawk_api_key%'
        is_hacker_allowed: '%is_hacker_allowed%'
        trusted_device_enabled: '%trusted_device_enabled%'
        trusted_device_cookie_lifetime: '%trusted_device_cookie_lifetime%'
        mintme_supply: '%mintme_supply%'
        show_full_data_in_profile: '%show_full_data_in_profile%'
        mintme_coin: '%mintme_coin%'
        mintme_coin_link: '%mintme_coin_link%'
        minimum_volume_for_marketcap: '%minimum_volume_for_marketcap%'
        landing_web_bonus: '%landing_web_bonus%'
        airdrop_params: '%airdrop_params%'
        global_contact_email: '%contact_email%'
        donation_params: '%donation%'
        withdraw_expiration_time: '%withdraw_expiration_time%'
